# Uncomment the next line to define a global platform for your project
install! 'cocoapods',
        :clean => true
        
platform :ios, '11.0'


target 'filmes_populares' do
  use_frameworks!
  pod "TMDBSwift"

  target 'filmes_popularesTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
